blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/jaschadub/AAEQ/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/jaschadub/AAEQ/blob/main/README.md
    about: Read the documentation and setup guides
